version: '3.8'

services:
  app:
    build: .
    container_name: meet_live_transcription
    ports:
      - "9020:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
